apiVersion: v1
kind: Service
metadata:
  name: db-postgresql
  namespace: db
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: db-port
      port: 5432
      protocol: TCP
      targetPort: 5432
