apiVersion: v1
kind: Endpoints
metadata:
  name: db-postgresql
  namespace: db
subsets:
  - addresses:
      - ip: 10.206.0.7
    ports:
      - name: db-port
        port: 5432
        protocol: TCP
