apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: db
spec:
  hard:
    requests.cpu: 1000m
    requests.memory: 2048Mi
    limits.cpu: 2000m
    limits.memory: 4Gi
    requests.storage: 50Gi
    persistentvolumeclaims: "5"
    pods: "20"
    configmaps: "20"
    secrets: "20"
    services: "10"
    services.loadbalancers: "0"
