name: push tags branches

on:
  push:
    tags:
      - "*"

jobs:
  apply:
    name: Set namespace
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: apply kustomize config
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.TKE_CONFIG_DATA_NJ }}
          command: apply -k overlays/production-plutus/
